/* ==========================================================================
   FLAVIO MODELS — models.js
   Fonte de dados dos modelos. Substitua "image" pelas fotos reais quando
   estiverem disponíveis — o restante da estrutura não muda.
   ========================================================================== */

const MODELS = [
  {
    id: 'alex-consain',
    name: 'Alex',
    surname: 'Consain',
    category: 'Mulheres',
    country: 'Brasil',
    age: 22,
    height: '1,78 m',
    weight: '54 kg',
    measurements: '84-61-89',
    eyes: 'Castanhos',
    hair: 'Loiro',
    phone: '5568999990001',
    instagram: 'alexconsain',
    image: 'imagens/imagem1.png',
    featured: true,
  },
  {
    id: 'gabriella-vieira',
    name: 'Gabriella',
    surname: 'Vieira',
    category: 'Teen',
    country: 'Brasil',
    age: 16,
    height: '1,72 m',
    weight: '50 kg',
    measurements: '80-58-86',
    eyes: 'Castanhos',
    hair: 'Castanho',
    phone: '5568999990002',
    instagram: 'gabriellavieira',
    image: 'imagens/image 36.png',
    featured: true,
  },
  {
    id: 'jose-e-jonas',
    name: 'José',
    surname: 'e Jonas',
    category: 'Homens',
    country: 'Brasil',
    age: 25,
    height: '1,88 m',
    weight: '78 kg',
    measurements: '96-82-94',
    eyes: 'Pretos',
    hair: 'Preto',
    phone: '5568999990001',
    instagram: 'jose&jonas',
    image: 'imagens/imagem2.png',
    featured: true,
  },
  {
    id: 'felca-santos',
    name: 'Felca',
    surname: 'Santos',
    category: 'Homens',
    country: 'Brasil',
    age: 24,
    height: '1,85 m',
    weight: '76 kg',
    measurements: '94-80-92',
    eyes: 'Castanhos',
    hair: 'Preto',
    phone: '5568999990001',
    instagram: 'felcaofc',
    image: 'imagens/image 15.png',
    featured: true,
  },
  {
    id: 'miranda-keer',
    name: 'Miranda',
    surname: 'Keer',
    category: 'Mulheres',
    country: 'Estados Unidos',
    age: 27,
    height: '1,80 m',
    weight: '56 kg',
    measurements: '86-62-90',
    eyes: 'Azuis',
    hair: 'Castanho',
    phone: '5568999990001',
    instagram: 'keermiranda',
    image: 'imagens/image 16.png',
    featured: true,
  },
  {
    id: 'felca-santos-2',
    name: 'Felca',
    surname: 'Santos',
    category: 'Homens',
    country: 'Brasil',
    age: 24,
    height: '1,85 m',
    weight: '76 kg',
    measurements: '94-80-92',
    eyes: 'Castanhos',
    hair: 'Preto',
    phone: '5568999990001',
    instagram: 'felcasantos',
    image: 'imagens/image 31.png',
    featured: true,
  },
  {
    id: 'andreia-gomes',
    name: 'Andreia',
    surname: 'Gomes',
    category: 'Mulheres',
    country: 'Brasil',
    age: 29,
    height: '1,76 m',
    weight: '55 kg',
    measurements: '85-60-88',
    eyes: 'Castanhos',
    hair: 'Preto',
    phone: '5568999990001',
    instagram: 'andreia',
    image: 'imagens/andreia-gomes.png',
    featured: true,
  },
  {
    id: 'alline',
    name: 'Alex',
    surname: 'Consain',
    category: 'Mulheres',
    country: 'Brasil',
    age: 22,
    height: '1,78 m',
    weight: '54 kg',
    measurements: '84-61-89',
    eyes: 'Castanhos',
    hair: 'Loiro',
    phone: '5568999990001',
    instagram: 'alline',
    image: 'imagens/image 24.png',
    featured: true,
  },
  {
    id: 'lara-fontoura',
    name: 'Lara',
    surname: 'Fontoura',
    category: 'Teen',
    country: 'Brasil',
    age: 15,
    height: '1,70 m',
    weight: '48 kg',
    measurements: '78-58-84',
    eyes: 'Verdes',
    hair: 'Castanho claro',
    phone: '5568999990001',
    instagram: 'laurafontuora',
    image: 'imagens/image 43.png',
    featured: false,
  },
  {
    id: 'thiago-moraes',
    name: 'Thiago',
    surname: 'Moraes',
    category: 'Teen',
    country: 'Brasil',
    age: 17,
    height: '1,82 m',
    weight: '66 kg',
    measurements: '90-76-90',
    eyes: 'Castanhos',
    hair: 'Preto',
    phone: '5568999990001',
    instagram: 'thiagomoraes',
    image: 'imagens/image 54.png',
    featured: false,
  },
  {
    id: 'piong-lee',
    name: 'Piong',
    surname: 'Lee',
    category: 'Homens',
    country: 'Coreia do Sul',
    age: 26,
    height: '1,86 m',
    weight: '74 kg',
    measurements: '92-78-92',
    eyes: 'Pretos',
    hair: 'Preto',
    phone: '5568999990001',
    instagram: 'leepiong',
    image: 'imagens/xayling.png',
    featured: false,
  },
  {
    id: 'hedi-ben',
    name: 'Hedi',
    surname: 'Ben',
    category: 'Homens',
    country: 'França',
    age: 23,
    height: '1,84 m',
    weight: '72 kg',
    measurements: '90-76-90',
    eyes: 'Castanhos',
    hair: 'Castanho',
    phone: '5568999990001',
    instagram: 'hedi',
    image: 'imagens/pyonglee.png',
    featured: false,
  },
  {
    id: 'latrel',
    name: 'Xu',
    surname: 'Meen',
    category: 'Homens',
    country: 'curacao',
    age: 24,
    height: '1,87 m',
    weight: '75 kg',
    measurements: '93-79-93',
    eyes: 'Pretos',
    hair: 'Preto',
    phone: '5568999990001',
    instagram: 'latrel',
    image: 'imagens/image 34.png',
    featured: false,
  },
  {
    id: 'xiru-yang',
    name: 'Xiru',
    surname: 'Yang',
    category: 'Mulheres',
    country: 'China',
    age: 25,
    height: '1,77 m',
    weight: '53 kg',
    measurements: '83-60-87',
    eyes: 'Pretos',
    hair: 'Preto',
    phone: '5568999990001',
    instagram: 'xiru',
    image: 'imagens/yiorra.png',
    featured: false,
  },
  {
    id: 'lya-santi',
    name: 'Lya',
    surname: 'Santi',
    category: 'Mulheres',
    country: 'Brasil',
    age: 21,
    height: '1,79 m',
    weight: '55 kg',
    measurements: '85-61-88',
    eyes: 'Castanhos',
    hair: 'Preto',
    phone: '5568999990001',
    instagram: 'lyasanti',
    image: 'imagens/image 25.png',
    featured: false,
  },
  {
    id: 'josefa-santos',
    name: 'Josefa',
    surname: 'Santos',
    category: 'Mulheres',
    country: 'Brasil',
    age: 28,
    height: '1,75 m',
    weight: '57 kg',
    measurements: '87-63-90',
    eyes: 'Castanhos',
    hair: 'Cacheado preto',
    phone: '5568999990001',
    instagram: 'josefa',
    image: 'imagens/image 38.png',
    featured: false,
  },
  {
    id: 'maria-ukech',
    name: 'Maria',
    surname: 'Ukech',
    category: 'Mulheres',
    country: 'Quênia',
    age: 24,
    height: '1,81 m',
    weight: '58 kg',
    measurements: '86-62-90',
    eyes: 'Castanhos',
    hair: 'Preto',
    phone: '5568999990001',
    instagram: 'mariauke',
    image: 'imagens/image 22.png',
    featured: false,
  },
  {
    id: 'loide-augusto',
    name: 'Loide',
    surname: 'Augusto',
    category: 'Homens',
    country: 'Angola',
    age: 26,
    height: '1,89 m',
    weight: '80 kg',
    measurements: '98-83-95',
    eyes: 'Pretos',
    hair: 'Preto',
    phone: '5568999990001',
    instagram: 'loide',
    image: 'imagens/image 32.png',
    featured: false,
  },
  {
    id: 'lucas-teen',
    name: 'Lucas',
    surname: 'Almeida',
    category: 'Teen',
    country: 'Brasil',
    age: 17,
    height: '1,82 m',
    weight: '64 kg',
    measurements: '90-74-90',
    eyes: 'Verdes',
    hair: 'Castanho',
    phone: '5568999990001',
    instagram: 'teenlucas',
    image: 'imagens/image 46.png',
    featured: false,
  },
];

const EVENTS = [
  { id: 'evento-1', title: 'Editorial Outono/Inverno', image: 'imagens/image 3.png' },
  { id: 'evento-2', title: 'Campanha Institucional', image: 'imagens/evento.png' },
  { id: 'evento-3', title: 'PRADA — Semana de Moda', image: 'imagens/prada.png' },
];
